#!/usr/bin/env bash
# Nexus Suite — one-command installer
# Usage: curl -fsSL https://raw.githubusercontent.com/pranavgawasproject/nexus-suite/main/install.sh | bash
#
# Clones the repo, generates secrets, and starts the stack with Docker Compose.
# Defaults to SQLite (single container). Pass --postgres for the Postgres profile.

set -euo pipefail

REPO="https://github.com/pranavgawasproject/nexus-suite.git"
DIR="nexus-suite"
PROFILE=""

# Parse args
for arg in "$@"; do
  case "$arg" in
    --postgres) PROFILE="--profile postgres" ;;
    --help|-h)
      echo "Nexus Suite installer"
      echo ""
      echo "Usage: curl -fsSL https://raw.githubusercontent.com/pranavgawasproject/nexus-suite/main/install.sh | bash -s -- [options]"
      echo ""
      echo "Options:"
      echo "  --postgres   Use PostgreSQL profile (with nightly backups) instead of SQLite"
      echo "  --help       Show this help"
      exit 0
      ;;
  esac
done

# Color output
green() { echo -e "\033[32m$1\033[0m"; }
yellow() { echo -e "\033[33m$1\033[0m"; }
red()   { echo -e "\033[31m$1\033[0m"; }

echo "╔══════════════════════════════════════════════════╗"
echo "║        Nexus Suite — Self-Host Installer         ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# Check prerequisites
command -v docker >/dev/null 2>&1 || { red "✗ Docker not found. Install: https://docs.docker.com/get-docker/"; exit 1; }
command -v git >/dev/null 2>&1 || { red "✗ git not found. Install: https://git-scm.com/"; exit 1; }

if ! docker compose version >/dev/null 2>&1; then
  red "✗ Docker Compose v2 not found. Install: https://docs.docker.com/compose/install/"
  exit 1
fi

green "✓ Docker + Docker Compose detected"

# Clone or update
if [ -d "$DIR" ]; then
  yellow "→ Directory '$DIR' exists — pulling latest..."
  cd "$DIR"
  git pull --rebase
else
  yellow "→ Cloning Nexus Suite..."
  git clone --depth 1 "$REPO" "$DIR"
  cd "$DIR"
fi

# Generate secrets
green "✓ Generating secrets..."
if [ ! -f .env ]; then
  cat > .env <<EOF
# Auto-generated by install.sh — edit as needed
NEXTAUTH_SECRET=$(openssl rand -base64 32 2>/dev/null || echo "CHANGE_ME_$(date +%s)")
NEXTAUTH_URL=http://localhost:3000
DATABASE_URL=file:/app/data/nexus.db
NEXUS_PORT=3000
EOF
  if [ -n "$PROFILE" ]; then
    PG_PASS=$(openssl rand -base64 24 2>/dev/null || echo "change_me")
    cat >> .env <<EOF
POSTGRES_USER=nexus
POSTGRES_PASSWORD=$PG_PASS
POSTGRES_DB=nexus
POSTGRES_PORT=5432
DATABASE_URL=postgresql://nexus:$PG_PASS@postgres:5432/nexus
EOF
  fi
  green "✓ .env created with random secrets"
else
  yellow "→ .env exists — keeping existing secrets"
fi

# Build + start
yellow "→ Building and starting containers (this takes 2-3 minutes on first run)..."
docker compose $PROFILE up -d --build

# Wait for healthcheck
green "✓ Waiting for app to be healthy..."
for i in $(seq 1 60); do
  if curl -sf http://localhost:3000/api/session >/dev/null 2>&1; then
    green "✓ Nexus Suite is up and healthy!"
    echo ""
    echo "╔══════════════════════════════════════════════════╗"
    echo "║                  ✅ READY ✅                     ║"
    echo "╠══════════════════════════════════════════════════╣"
    echo "║                                                  ║"
    echo "║  Open: http://localhost:3000                     ║"
    echo "║                                                  ║"
    echo "║  Demo login: any email + password 'demo'         ║"
    echo "║  (e.g. priya@acme.test)                          ║"
    echo "║                                                  ║"
    echo "║  Logs: docker compose logs -f                    ║"
    echo "║  Stop: docker compose down                       ║"
    echo "║  Update: ./install.sh (re-run)                   ║"
    echo "║                                                  ║"
    echo "╚══════════════════════════════════════════════════╝"
    exit 0
  fi
  sleep 2
done

red "✗ App did not become healthy within 120s. Check logs:"
red "  docker compose logs nexus"
exit 1
